version: "2"
run:
  timeout: 240m
  go: "1.24"
  modules-download-mode: readonly
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
    junit-xml:
      path: report.xml
linters:
  default: all
  disable:
    - wsl
    - depguard
    - exhaustruct
    - paralleltest
    - testpackage
    - noinlineerr
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
