kind: Release
apiVersion: appstudio.redhat.com/v1alpha1
metadata:
  generateName: agentic-cluster-security-suite-X-Y--X-Y-Z--RELEASE_ENV-
  namespace: agentic-cluster-security-suite-tenant
  labels:
    release.appstudio.openshift.io/automated: "false"
    release.appstudio.openshift.io/author: "RELEASE_AUTHOR"
spec:
  releasePlan: agentic-cluster-security-suite-RELEASE_ENV-X-Y
  snapshot: WARNING-replace-before-create-WARNING
  data:
    mapping:
      defaults:
        tags:
          - "X.Y"
          - "X.Y.Z"
          - "X.Y.Z-{{ incrementer }}"
    releaseNotes:
      type: RHEA
      references:
        - 'https://github.com/stackrox/stackrox-mcp/blob/main/README.md#quick-start'
        - 'https://github.com/stackrox/stackrox-mcp/releases/tag/X.Y.Z'
