apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/stackrox-mcp?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
    pipelinesascode.tekton.dev/on-label: "[]"
    # - body.action != "ready_for_review" prevents double-triggering when a draft PR is marked ready for review.
    # - trigger only for PRs on main and release branches.
    # - support triggering by label: "konflux-build"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        event == "pull_request" && body.action != "ready_for_review" && (
          target_branch == "main" ||
          target_branch.startsWith("release-") ||
          (
            has(body.pull_request) && 
            has(body.pull_request.labels) && 
            body.pull_request.labels.exists(l, l.name == "konflux-build")
          )
        )
      )
  labels:
    appstudio.openshift.io/application: agentic-cluster-security-suite
    appstudio.openshift.io/component: acs-mcp-server
    pipelines.appstudio.openshift.io/type: build
  name: acs-mcp-server-on-pull-request
  namespace: agentic-cluster-security-suite-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image-repo
    value: quay.io/redhat-user-workloads/agentic-cluster-security-suite-tenant/acs-mcp-server
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: konflux.Dockerfile
  - name: hermetic
    value: 'true'
  - name: prefetch-input
    value: |
      [
        { "type": "gomod", "path": "." },
        { "type": "rpm", "path": "." }
      ]
  - name: clone-depth
    value: '0'
  - name: clone-fetch-tags
    value: 'true'
  - name: extra-labels
    value:
    # X.Y in the cpe label must be adjusted for every version stream.
    - "cpe=cpe:/a:redhat:agentic_cluster_security_suite:X.Y::el9"

  pipelineRef:
    name: basic-component-pipeline

  taskRunTemplate:
    serviceAccountName: build-pipeline-acs-mcp-server

  timeouts:
    tasks: 1h
    finally: 10m
    pipeline: 1h10m

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
